/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class frc_robot_vision_Pixy2USBJNI */

#ifndef _Included_frc_robot_vision_Pixy2USBJNI
#define _Included_frc_robot_vision_Pixy2USBJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     frc_robot_vision_Pixy2USBJNI
 * Method:    pixy2USBInit
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_frc_robot_vision_Pixy2USBJNI_pixy2USBInit
  (JNIEnv *, jobject);

/*
 * Class:     frc_robot_vision_Pixy2USBJNI
 * Method:    pixy2USBGetVersion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frc_robot_vision_Pixy2USBJNI_pixy2USBGetVersion
  (JNIEnv *, jobject);

/*
 * Class:     frc_robot_vision_Pixy2USBJNI
 * Method:    pixy2USBLampOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frc_robot_vision_Pixy2USBJNI_pixy2USBLampOn
  (JNIEnv *, jobject);

/*
 * Class:     frc_robot_vision_Pixy2USBJNI
 * Method:    pixy2USBLampOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frc_robot_vision_Pixy2USBJNI_pixy2USBLampOff
  (JNIEnv *, jobject);

/*
 * Class:     frc_robot_vision_Pixy2USBJNI
 * Method:    pixy2USBStartCameraServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frc_robot_vision_Pixy2USBJNI_pixy2USBStartCameraServer
  (JNIEnv *, jobject);

/*
 * Class:     frc_robot_vision_Pixy2USBJNI
 * Method:    pixy2USBLoopCameraServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_frc_robot_vision_Pixy2USBJNI_pixy2USBLoopCameraServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
